# Generated by Django 4.2.7 on 2025-11-12 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_spreadsheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_spreadsheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
